### ISSUE TITLE
File name - Class name mismatch

### ISSUE THREAD

**Issue by sigmarsson** [Obalix/NGeo#1]
https://github.com/Obalix/NGeo2/blob/master/NGeo2.Shared/GeoNames/Requests/FindGeoNameRequest.cs

**Comment by Obalix** [comment]
Could you be a bit more specific please.

**Comment by Obalix** [comment]
Sorry found it in your pull request.

**Comment by Obalix** [comment]
Merged into dev branch with 17ae0dff6e00820995c706152a1cc615bcc1865c
